# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.0-node-browsers
         environment:
            PGHOST: 127.0.0.1
            PGUSER: db-user
            RAILS_ENV: test
            DISABLE_SPRING: true
       - image: circleci/postgres:9.4
         environment:
            POSTGRES_USER: db-user
            POSTGRES_DB: zero-rails_test
            POSTGRES_PASSWORD: ""

    working_directory: ~/zero-rails

    steps:
      - checkout

      # Download and cache ruby dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Download and cache js dependencies
      - restore_cache:
          key: npm-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: npm-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # copy config fiels

      - run: cp config/database.example.yml config/database.yml
      - run: cp config/secrets.example.yml config/secrets.yml
      # Database setup
      - run: bundle exec rake db:setup

      # run tests!
      - run: bundle exec rails test
